/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#261900",
        "tertiary": "#775a19",
        "surface-dim": "#dbdad6",
        "background": "#faf9f5",
        "surface-bright": "#faf9f5",
        "on-surface-variant": "#55433c",
        "surface-container-high": "#e9e8e4",
        "primary-container": "#d97d54",
        "tertiary-container": "#b3904b",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#5d4201",
        "charcoal-ink": "#1A1A1A",
        "surface": "#faf9f5",
        "primary": "#964824",
        "inverse-surface": "#2f312e",
        "on-primary-fixed": "#360f00",
        "tertiary-fixed-dim": "#e9c176",
        "on-secondary-fixed-variant": "#384b3f",
        "inverse-primary": "#ffb597",
        "outline-variant": "#dac1b8",
        "inverse-on-surface": "#f2f1ed",
        "surface-container-highest": "#e3e2df",
        "deep-earth": "#3D2B1F",
        "soft-clay": "#E9E4D9",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#77320e",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "secondary-container": "#cfe5d4",
        "primary-fixed-dim": "#ffb597",
        "on-primary-container": "#541c00",
        "on-error": "#ffffff",
        "on-background": "#1b1c1a",
        "secondary-fixed-dim": "#b6ccbb",
        "surface-tint": "#964824",
        "surface-container-low": "#f4f4f0",
        "primary-fixed": "#ffdbcd",
        "surface-variant": "#e3e2df",
        "on-secondary-fixed": "#0d1f15",
        "secondary-fixed": "#d2e8d7",
        "on-secondary-container": "#53675a",
        "surface-container": "#efeeea",
        "tertiary-fixed": "#ffdea5",
        "outline": "#87736b",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#4f6356",
        "on-tertiary-container": "#3d2a00",
        "error-container": "#ffdad6",
        "on-surface": "#1b1c1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "8px",
        "section-gap": "120px",
        "gutter": "32px",
        "container-max-width": "1280px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "body-lg": ["Manrope"],
        "quote": ["Playfair Display"],
        "body-md": ["Manrope"],
        "headline-lg-mobile": ["Playfair Display"],
        "label-caps": ["Manrope"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "quote": ["24px", { lineHeight: "36px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
