import type { User } from '../types/user.type';
import type { Workshop } from '../types/workshop.type';
import type { Product } from '../types/product.type';
import type { Booking } from '../types/booking.type';
import type { Order } from '../types/order.type';
import type { Timeslot } from '../types/timeslot.type';
import type { Review } from '../types/review.type';

// ========== CATEGORIES ==========
export const categories = [
  { id: '1', name: 'Làm gốm', icon: '🏺', count: 24, slug: 'pottery' },
  { id: '2', name: 'Làm đèn lồng', icon: '🏮', count: 18, slug: 'lantern-making' },
  { id: '3', name: 'Dệt vải', icon: '🧵', count: 15, slug: 'textile-weaving' },
  { id: '4', name: 'Vẽ tranh', icon: '🎨', count: 21, slug: 'painting' },
  { id: '5', name: 'Điêu khắc gỗ', icon: '🪵', count: 12, slug: 'woodcarving' },
  { id: '6', name: 'Nấu ăn', icon: '🍜', count: 30, slug: 'cooking' },
  { id: '7', name: 'Thư pháp', icon: '✒️', count: 9, slug: 'calligraphy' },
  { id: '8', name: 'Đan tre', icon: '🎋', count: 7, slug: 'bamboo-craft' },
];

// ========== TRUST BAR ==========
export const trustItems = [
  { label: '500+', sublabel: 'Workshop văn hóa', icon: 'palette' },
  { label: '200+', sublabel: 'Nghệ nhân địa phương', icon: 'people' },
  { label: 'QR', sublabel: 'Check-in nhanh chóng', icon: 'qr_code_scanner' },
  { label: 'VNPay', sublabel: 'Thanh toán an toàn', icon: 'payments' },
  { label: '4.9★', sublabel: 'Đánh giá trung bình', icon: 'star' },
];

// ========== WORKSHOPS ==========
export const workshops: Workshop[] = [
  {
    _id: 'ws-001',
    title: 'Làm gốm truyền thống tại Bát Tràng',
    description: 'Học nghệ thuật làm gốm hàng trăm năm tuổi từ các nghệ nhân bậc thầy tại làng gốm Bát Tràng nổi tiếng. Nặn đất trên bàn xoay truyền thống, vẽ họa tiết Việt Nam chính gốc, và mang về tác phẩm độc đáo của riêng bạn. Trải nghiệm đắm chìm này kết nối bạn với một trong những truyền thống thủ công quý giá nhất của Việt Nam có lịch sử hơn 700 năm.',
    category: 'Làm gốm',
    price: 450000,
    duration: 180,
    address: '15 Làng Bát Tràng, Gia Lâm',
    location: 'Hà Nội',
    images: ['/src/assets/images/pottery-workshop.jpg'],
    hostId: 'host-001',
    hostName: 'Nghệ nhân Nguyễn Văn Toàn',
    hostAvatar: '',
    status: 'ACTIVE',
    rating: 4.8,
    totalReviews: 124,
    maxGuests: 12,
    includes: ['Nguyên liệu đầy đủ', 'Dịch vụ nung gốm', 'Trà truyền thống', 'Giấy chứng nhận'],
    requirements: ['Không cần kinh nghiệm', 'Mặc trang phục thoải mái'],
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    _id: 'ws-002',
    title: 'Làm đèn lồng lụa tại Hội An',
    description: 'Tự tay làm chiếc đèn lồng lụa tuyệt đẹp dưới sự hướng dẫn của những nghệ nhân làm đèn lồng giỏi nhất Hội An. Chọn từ nhiều loại lụa rực rỡ, học kỹ thuật khung tre, và tạo nên tác phẩm phát sáng để trang trí nhà bạn. Trải nghiệm sự kỳ diệu khiến Phố cổ Hội An lung linh mỗi tối.',
    category: 'Làm đèn lồng',
    price: 350000,
    duration: 120,
    address: '48 đường Trần Phú, Phố cổ',
    location: 'Hội An',
    images: ['/src/assets/images/lantern-workshop.jpg'],
    hostId: 'host-002',
    hostName: 'Nghệ nhân Lê Thị Mai',
    status: 'ACTIVE',
    rating: 4.9,
    totalReviews: 89,
    maxGuests: 8,
    includes: ['Nguyên liệu lụa & tre', 'Đèn LED', 'Túi đựng'],
    createdAt: '2025-02-20T09:00:00Z',
    updatedAt: '2025-06-10T11:00:00Z',
  },
  {
    _id: 'ws-003',
    title: 'Đan tre miền Trung Việt Nam',
    description: 'Khám phá nghệ thuật đan tre cổ xưa cùng những nghệ nhân đã hoàn thiện kỹ năng qua nhiều thế hệ. Học cách tạo ra rổ, khay và đồ trang trí truyền thống từ nan tre bền vững. Một trải nghiệm thiền định và đáng giá.',
    category: 'Đan tre',
    price: 380000,
    duration: 150,
    address: '22 đường Lê Lợi',
    location: 'Đà Nẵng',
    images: ['/src/assets/images/textile-workshop.jpg'],
    hostId: 'host-003',
    hostName: 'Nghệ nhân Phạm Đức',
    status: 'ACTIVE',
    rating: 4.7,
    totalReviews: 56,
    maxGuests: 10,
    includes: ['Nguyên liệu tre', 'Dụng cụ', 'Đồ ăn nhẹ & nước uống'],
    createdAt: '2025-03-10T07:00:00Z',
    updatedAt: '2025-06-05T08:00:00Z',
  },
  {
    _id: 'ws-004',
    title: 'Hương vị Huế: Nấu ăn cung đình',
    description: 'Bước vào thế giới hương vị của kinh đô xưa. Nấu các món Huế chính gốc bao gồm Bún Bò Huế, Bánh Khoái, và Chè Huế cùng đầu bếp địa phương. Tham quan chợ sáng, chọn nguyên liệu tươi, và thuần thục sự cân bằng giữa cay, chua, ngọt, mặn đặc trưng ẩm thực Huế.',
    category: 'Nấu ăn',
    price: 520000,
    duration: 240,
    address: '7 Nguyễn Tri Phương, Huế',
    location: 'Huế',
    images: ['/src/assets/images/pottery-workshop.jpg'],
    hostId: 'host-004',
    hostName: 'Đầu bếp Trần Thị Lan',
    status: 'ACTIVE',
    rating: 4.9,
    totalReviews: 203,
    maxGuests: 8,
    includes: ['Tour chợ sáng', 'Đầy đủ nguyên liệu', 'Sổ tay công thức', 'Bữa ăn trọn bộ'],
    createdAt: '2025-01-25T06:00:00Z',
    updatedAt: '2025-06-12T09:00:00Z',
  },
  {
    _id: 'ws-005',
    title: 'Nghệ thuật Thư pháp Việt Nam',
    description: 'Làm chủ những nét bút thanh thoát của thư pháp Việt Nam. Học cả thư pháp chữ Hán truyền thống và thư pháp chữ Quốc Ngữ hiện đại. Tự tay viết câu đối với những câu tục ngữ và lời chúc ý nghĩa.',
    category: 'Thư pháp',
    price: 300000,
    duration: 120,
    address: '12 đường Văn Miếu',
    location: 'Hà Nội',
    images: ['/src/assets/images/lantern-workshop.jpg'],
    hostId: 'host-001',
    hostName: 'Nghệ nhân Nguyễn Văn Toàn',
    status: 'ACTIVE',
    rating: 4.6,
    totalReviews: 45,
    maxGuests: 15,
    includes: ['Bộ bút & mực', 'Giấy dó', 'Giấy luyện tập'],
    createdAt: '2025-04-01T08:00:00Z',
    updatedAt: '2025-06-08T10:00:00Z',
  },
  {
    _id: 'ws-006',
    title: 'Workshop vẽ tranh lụa Áo Dài',
    description: 'Vẽ các họa tiết truyền thống Việt Nam trên vải lụa, dưới sự hướng dẫn của họa sĩ tranh lụa giàu kinh nghiệm. Tìm hiểu ý nghĩa của hoa sen, rồng và phong cảnh trong nghệ thuật Việt Nam. Bức tranh lụa của bạn có thể được đóng khung như một tác phẩm nghệ thuật.',
    category: 'Vẽ tranh',
    price: 400000,
    duration: 150,
    address: '88 đường Đồng Khởi',
    location: 'TP. Hồ Chí Minh',
    images: ['/src/assets/images/textile-workshop.jpg'],
    hostId: 'host-002',
    hostName: 'Nghệ nhân Lê Thị Mai',
    status: 'ACTIVE',
    rating: 4.8,
    totalReviews: 67,
    maxGuests: 10,
    includes: ['Canvas lụa', 'Bộ sơn & cọ vẽ', 'Khung tranh'],
    createdAt: '2025-03-15T07:00:00Z',
    updatedAt: '2025-06-01T11:00:00Z',
  },
];

// ========== PRODUCTS ==========
export const products: Product[] = [
  {
    _id: 'prod-001',
    name: 'Bình gốm Bát Tràng thủ công',
    description: 'Bình gốm thủ công tuyệt đẹp với hoa văn men trắng xanh truyền thống. Mỗi sản phẩm đều là độc nhất, được chế tác bởi các nghệ nhân bậc thầy tại làng gốm Bát Tràng.',
    price: 850000,
    stock: 15,
    category: 'Gốm sứ',
    images: ['/src/assets/images/ceramic-product.jpg'],
    hostId: 'host-001',
    hostName: 'Nghệ nhân Nguyễn Văn Toàn',
    status: 'ACTIVE',
    rating: 4.9,
    totalReviews: 34,
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    _id: 'prod-002',
    name: 'Đèn lồng lụa Hội An - Cỡ vừa',
    description: 'Đèn lồng lụa Hội An chính gốc, làm thủ công với khung tre và lụa cao cấp. Hoàn hảo để trang trí nhà hoặc làm quà tặng độc đáo. Đi kèm đèn LED.',
    price: 420000,
    stock: 25,
    category: 'Tre nứa',
    images: ['/src/assets/images/lantern-workshop.jpg'],
    hostId: 'host-002',
    hostName: 'Nghệ nhân Lê Thị Mai',
    status: 'ACTIVE',
    rating: 4.8,
    totalReviews: 56,
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2025-06-05T11:00:00Z',
  },
  {
    _id: 'prod-003',
    name: 'Khăn thổ cẩm dệt tay',
    description: 'Khăn thổ cẩm truyền thống được dệt bởi các nghệ nhân dân tộc thiểu số tại Sa Pa. Làm từ thuốc nhuộm tự nhiên với hoa văn tinh xảo kể câu chuyện cuộc sống vùng cao.',
    price: 650000,
    stock: 10,
    category: 'Dệt may',
    images: ['/src/assets/images/textile-workshop.jpg'],
    hostId: 'host-003',
    hostName: 'Nghệ nhân Phạm Đức',
    status: 'ACTIVE',
    rating: 4.7,
    totalReviews: 23,
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2025-06-10T08:00:00Z',
  },
  {
    _id: 'prod-004',
    name: 'Hộp trang sức sơn mài',
    description: 'Hộp sơn mài tinh xảo khảm xà cừ. Chế tác thủ công bằng kỹ thuật sơn mài truyền thống Việt Nam, mất nhiều tuần để hoàn thành.',
    price: 1200000,
    stock: 8,
    category: 'Sơn mài',
    images: ['/src/assets/images/ceramic-product.jpg'],
    hostId: 'host-001',
    hostName: 'Nghệ nhân Nguyễn Văn Toàn',
    status: 'ACTIVE',
    rating: 5.0,
    totalReviews: 12,
    createdAt: '2025-05-01T07:00:00Z',
    updatedAt: '2025-06-12T09:00:00Z',
  },
  {
    _id: 'prod-005',
    name: 'Bộ trà tre',
    description: 'Bộ trà hoàn chỉnh làm từ tre bền vững. Bao gồm ấm trà, bốn chén và khay phục vụ. Hoàn hảo cho nghi thức thưởng trà kiểu Việt Nam.',
    price: 580000,
    stock: 20,
    category: 'Tre nứa',
    images: ['/src/assets/images/pottery-workshop.jpg'],
    hostId: 'host-003',
    hostName: 'Nghệ nhân Phạm Đức',
    status: 'ACTIVE',
    rating: 4.6,
    totalReviews: 18,
    createdAt: '2025-04-15T08:00:00Z',
    updatedAt: '2025-06-08T10:00:00Z',
  },
  {
    _id: 'prod-006',
    name: 'Khăn lụa vẽ tay',
    description: 'Khăn lụa thanh lịch được vẽ tay với họa tiết hoa sen Việt Nam. Mỗi chiếc khăn là một tác phẩm nghệ thuật có thể mang, độc đáo và không lặp lại.',
    price: 780000,
    stock: 12,
    category: 'Dệt may',
    images: ['/src/assets/images/textile-workshop.jpg'],
    hostId: 'host-002',
    hostName: 'Nghệ nhân Lê Thị Mai',
    status: 'ACTIVE',
    rating: 4.8,
    totalReviews: 29,
    createdAt: '2025-03-20T09:00:00Z',
    updatedAt: '2025-06-06T11:00:00Z',
  },
];

// ========== USERS ==========
export const users: User[] = [
  {
    _id: 'admin-001',
    fullName: 'Quản trị viên',
    email: 'admin@craftlocal.vn',
    phone: '0901234567',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-06-01T00:00:00Z',
  },
  {
    _id: 'host-001',
    fullName: 'Nghệ nhân Nguyễn Văn Toàn',
    email: 'toan@craftlocal.vn',
    phone: '0912345678',
    role: 'HOST',
    status: 'ACTIVE',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    _id: 'host-002',
    fullName: 'Nghệ nhân Lê Thị Mai',
    email: 'mai@craftlocal.vn',
    phone: '0923456789',
    role: 'HOST',
    status: 'ACTIVE',
    createdAt: '2025-02-01T09:00:00Z',
    updatedAt: '2025-06-05T11:00:00Z',
  },
  {
    _id: 'host-003',
    fullName: 'Nghệ nhân Phạm Đức',
    email: 'duc@craftlocal.vn',
    phone: '0934567890',
    role: 'HOST',
    status: 'PENDING',
    createdAt: '2025-06-01T07:00:00Z',
    updatedAt: '2025-06-01T07:00:00Z',
  },
  {
    _id: 'tourist-001',
    fullName: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '0945678901',
    role: 'TOURIST',
    status: 'ACTIVE',
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: '2025-06-10T08:00:00Z',
  },
  {
    _id: 'tourist-002',
    fullName: 'James Wilson',
    email: 'james@example.com',
    phone: '0956789012',
    role: 'TOURIST',
    status: 'ACTIVE',
    createdAt: '2025-04-01T11:00:00Z',
    updatedAt: '2025-06-12T09:00:00Z',
  },
  {
    _id: 'guide-001',
    fullName: 'Tran Minh Duc',
    email: 'minh@craftlocal.vn',
    phone: '0967890123',
    role: 'TOUR_GUIDE',
    status: 'ACTIVE',
    hostId: 'host-001',
    createdAt: '2025-02-15T08:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    _id: 'guide-002',
    fullName: 'Nguyen Hoang Anh',
    email: 'anh@craftlocal.vn',
    phone: '0978901234',
    role: 'TOUR_GUIDE',
    status: 'ACTIVE',
    hostId: 'host-002',
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2025-06-05T11:00:00Z',
  },
];

// ========== TIMESLOTS ==========
export const timeslots: Timeslot[] = [
  {
    _id: 'ts-001',
    workshopId: 'ws-001',
    workshopTitle: 'Làm gốm truyền thống tại Bát Tràng',
    date: '2025-06-20',
    startTime: '09:00',
    endTime: '12:00',
    totalSlots: 12,
    bookedSlots: 8,
    availableSlots: 4,
    status: 'AVAILABLE',
    tourGuideId: 'guide-001',
    tourGuideName: 'Tran Minh Duc',
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    _id: 'ts-002',
    workshopId: 'ws-001',
    workshopTitle: 'Làm gốm truyền thống tại Bát Tràng',
    date: '2025-06-20',
    startTime: '14:00',
    endTime: '17:00',
    totalSlots: 12,
    bookedSlots: 12,
    availableSlots: 0,
    status: 'FULL',
    tourGuideId: 'guide-001',
    tourGuideName: 'Tran Minh Duc',
    createdAt: '2025-06-01T08:00:00Z',
  },
  {
    _id: 'ts-003',
    workshopId: 'ws-002',
    workshopTitle: 'Làm đèn lồng lụa tại Hội An',
    date: '2025-06-21',
    startTime: '10:00',
    endTime: '12:00',
    totalSlots: 8,
    bookedSlots: 3,
    availableSlots: 5,
    status: 'AVAILABLE',
    tourGuideId: 'guide-002',
    tourGuideName: 'Nguyen Hoang Anh',
    createdAt: '2025-06-02T09:00:00Z',
  },
  {
    _id: 'ts-004',
    workshopId: 'ws-003',
    workshopTitle: 'Đan tre miền Trung Việt Nam',
    date: '2025-06-22',
    startTime: '08:30',
    endTime: '11:00',
    totalSlots: 10,
    bookedSlots: 5,
    availableSlots: 5,
    status: 'AVAILABLE',
    createdAt: '2025-06-03T07:00:00Z',
  },
  {
    _id: 'ts-005',
    workshopId: 'ws-004',
    workshopTitle: 'Hương vị Huế: Nấu ăn cung đình',
    date: '2025-06-23',
    startTime: '07:00',
    endTime: '11:00',
    totalSlots: 8,
    bookedSlots: 6,
    availableSlots: 2,
    status: 'AVAILABLE',
    tourGuideId: 'guide-001',
    tourGuideName: 'Tran Minh Duc',
    createdAt: '2025-06-04T06:00:00Z',
  },
];

// ========== BOOKINGS ==========
export const bookings: Booking[] = [
  {
    _id: 'bk-001',
    workshopId: 'ws-001',
    workshopTitle: 'Làm gốm truyền thống tại Bát Tràng',
    workshopImage: '/src/assets/images/pottery-workshop.jpg',
    timeslotId: 'ts-001',
    timeslotDate: '2025-06-20',
    timeslotStartTime: '09:00',
    timeslotEndTime: '12:00',
    touristId: 'tourist-001',
    touristName: 'Sarah Johnson',
    touristEmail: 'sarah@example.com',
    guests: 2,
    totalAmount: 900000,
    status: 'PAID',
    qrCode: 'BK-001-CRAFT-2025',
    createdAt: '2025-06-10T14:00:00Z',
    updatedAt: '2025-06-10T14:30:00Z',
  },
  {
    _id: 'bk-002',
    workshopId: 'ws-002',
    workshopTitle: 'Làm đèn lồng lụa tại Hội An',
    workshopImage: '/src/assets/images/lantern-workshop.jpg',
    timeslotId: 'ts-003',
    timeslotDate: '2025-06-21',
    timeslotStartTime: '10:00',
    timeslotEndTime: '12:00',
    touristId: 'tourist-001',
    touristName: 'Sarah Johnson',
    guests: 1,
    totalAmount: 350000,
    status: 'COMPLETED',
    qrCode: 'BK-002-CRAFT-2025',
    checkedInAt: '2025-06-21T09:55:00Z',
    createdAt: '2025-06-12T10:00:00Z',
    updatedAt: '2025-06-21T12:00:00Z',
  },
  {
    _id: 'bk-003',
    workshopId: 'ws-004',
    workshopTitle: 'Hương vị Huế: Nấu ăn cung đình',
    timeslotId: 'ts-005',
    timeslotDate: '2025-06-23',
    timeslotStartTime: '07:00',
    timeslotEndTime: '11:00',
    touristId: 'tourist-002',
    touristName: 'James Wilson',
    guests: 3,
    totalAmount: 1560000,
    status: 'PENDING',
    qrCode: 'BK-003-CRAFT-2025',
    createdAt: '2025-06-15T09:00:00Z',
    updatedAt: '2025-06-15T09:00:00Z',
  },
];

// ========== ORDERS ==========
export const orders: Order[] = [
  {
    _id: 'ord-001',
    touristId: 'tourist-001',
    touristName: 'Sarah Johnson',
    items: [
      { productId: 'prod-001', productName: 'Bình gốm Bát Tràng thủ công', price: 850000, quantity: 1 },
      { productId: 'prod-002', productName: 'Đèn lồng lụa Hội An - Cỡ vừa', price: 420000, quantity: 2 },
    ],
    shippingAddress: '123 Nguyen Hue Street, District 1, Ho Chi Minh City',
    shippingFee: 30000,
    totalAmount: 1720000,
    status: 'COMPLETED',
    paymentMethod: 'VNPay',
    createdAt: '2025-06-05T10:00:00Z',
    updatedAt: '2025-06-12T15:00:00Z',
  },
  {
    _id: 'ord-002',
    touristId: 'tourist-002',
    touristName: 'James Wilson',
    items: [
      { productId: 'prod-003', productName: 'Khăn thổ cẩm dệt tay', price: 650000, quantity: 1 },
    ],
    shippingAddress: '45 Le Duan Boulevard, Hanoi',
    shippingFee: 30000,
    totalAmount: 680000,
    status: 'SHIPPING',
    paymentMethod: 'MoMo',
    createdAt: '2025-06-10T08:00:00Z',
    updatedAt: '2025-06-14T11:00:00Z',
  },
];

// ========== REVIEWS ==========
export const reviews: Review[] = [
  {
    _id: 'rev-001',
    bookingId: 'bk-002',
    workshopId: 'ws-002',
    workshopTitle: 'Làm đèn lồng lụa tại Hội An',
    touristId: 'tourist-001',
    touristName: 'Sarah Johnson',
    rating: 5,
    comment: 'Trải nghiệm tuyệt vời! Nghệ nhân rất kiên nhẫn và tài hoa. Tôi rất yêu chiếc đèn lồng và nó đang treo tự hào trong phòng khách của tôi. Rất đáng để thử!',
    createdAt: '2025-06-22T08:00:00Z',
  },
  {
    _id: 'rev-002',
    bookingId: 'bk-001',
    workshopId: 'ws-001',
    workshopTitle: 'Làm gốm truyền thống tại Bát Tràng',
    touristId: 'tourist-002',
    touristName: 'James Wilson',
    rating: 4,
    comment: 'Workshop tuyệt vời! Bàn xoay gốm hơi khó lúc đầu nhưng nghệ nhân rất nhiệt tình hướng dẫn. Trà được phục vụ trong giờ giải lao rất ngon.',
    createdAt: '2025-06-23T10:00:00Z',
  },
  {
    _id: 'rev-003',
    bookingId: 'bk-003',
    workshopId: 'ws-004',
    workshopTitle: 'Hương vị Huế: Nấu ăn cung đình',
    touristId: 'tourist-001',
    touristName: 'Sarah Johnson',
    rating: 5,
    comment: 'Lớp nấu ăn quá tuyệt vời! Đầu bếp Lan không chỉ dạy công thức mà còn kể lịch sử đằng sau mỗi món ăn. Tour chợ sáng là điểm nhấn. Chúng tôi đã nấu và ăn như vua chúa.',
    createdAt: '2025-06-24T12:00:00Z',
  },
];

// ========== TOUR GUIDES ==========
export const tourGuides = [
  {
    _id: 'guide-001',
    fullName: 'Tran Minh Duc',
    email: 'minh@craftlocal.vn',
    phone: '0967890123',
    hostId: 'host-001',
    status: 'ACTIVE' as const,
    assignedTimeslots: ['ts-001', 'ts-002', 'ts-005'],
    createdAt: '2025-02-15T08:00:00Z',
  },
  {
    _id: 'guide-002',
    fullName: 'Nguyen Hoang Anh',
    email: 'anh@craftlocal.vn',
    phone: '0978901234',
    hostId: 'host-002',
    status: 'ACTIVE' as const,
    assignedTimeslots: ['ts-003'],
    createdAt: '2025-03-01T09:00:00Z',
  },
];

// ========== DASHBOARD STATS ==========
export const dashboardStats = {
  admin: {
    totalUsers: 156,
    totalHosts: 24,
    totalBookings: 1247,
    totalRevenue: 458000000,
    monthlyRevenue: [
      { month: 'Jan', revenue: 28000000 },
      { month: 'Feb', revenue: 35000000 },
      { month: 'Mar', revenue: 42000000 },
      { month: 'Apr', revenue: 38000000 },
      { month: 'May', revenue: 51000000 },
      { month: 'Jun', revenue: 48000000 },
    ],
  },
  host: {
    todayBookings: 8,
    monthlyRevenue: 12500000,
    activeWorkshops: 4,
    pendingOrders: 3,
    monthlyRevChart: [
      { month: 'Jan', revenue: 8500000 },
      { month: 'Feb', revenue: 9200000 },
      { month: 'Mar', revenue: 11000000 },
      { month: 'Apr', revenue: 10500000 },
      { month: 'May', revenue: 13200000 },
      { month: 'Jun', revenue: 12500000 },
    ],
  },
  tourGuide: {
    todaySchedule: 2,
    totalCustomers: 15,
    nextTimeslot: '09:00 - 12:00',
    completedTrips: 47,
  },
};
